-- require("plug-config.completion")
require("plug-config.dashboard")
require("plug-config.format")
require("plug-config.git")
require("plug-config.lsp")
require("plug-config.nvimtree")
require("plug-config.telescope")
require("plug-config.term")
require("plug-config.todocomments")
require("plug-config.treesitter")
require("plug-config.whichkey")
